Repository TeamFunxtion/fx-frontend, pull requests merged in 2024-05, with the labels that each got.

#9 Feature/#5 상품 등록,수정화면 퍼블리싱
  .github/ISSUE_TEMPLATE/bug.md
  .github/ISSUE_TEMPLATE/feature.md
  .github/ISSUE_TEMPLATE/fix.md
  src/app/(products)/products/[id]/edit/page.tsx
  src/app/(products)/products/new/page.tsx
  src/components/products/ProductsNewForm.module.css
  src/components/products/ProductsNewForm.tsx
Labels: ✨ Feat

#13 [#8] style : 공지사항화면 디자인
  src/app/(notice)/notice/page.module.css
  src/app/(notice)/notice/page.tsx
Labels: ✨ Feat

#15 Feature/#11
  src/app/(products)/products/[id]/page.module.css
  src/app/(products)/products/[id]/page.tsx
  src/app/search/page.module.css
  src/app/search/page.tsx
  src/components/ProductCard.tsx
  src/components/search/ProductSearchFilter.tsx
  src/styles/ProductCard.module.css
  src/styles/search/ProductSearchFilter.module.css
Labels: ✨ Feat

#18 [#6] Feat : 내정보수정 퍼블리싱
  src/app/(auth)/auth/join/page.tsx
  src/app/(shop)/shop/update/page.module.css
  src/app/(shop)/shop/update/page.tsx
  src/components/shop/shop-menubar.tsx
Labels: ✨ Feat

#21 Feature/#20 1대1 채팅 퍼블리싱
  src/app/(chats)/chats/[id]/page.module.css
  src/app/(chats)/chats/[id]/page.tsx
  src/app/(chats)/chats/layout.module.css
  src/app/(chats)/chats/layout.tsx
  src/app/(chats)/chats/page.tsx
  src/components/chats/Chats.tsx
Labels: ✨ Feat

#25 [Feat] 로그인,회원가입 기능
  package-lock.json
  package.json
  public/images/oauth/kakao_login_large_wide.png
  src/app/(auth)/auth/join/page.tsx
  src/app/(auth)/auth/login/page.module.css
  src/app/(auth)/auth/login/page.tsx
  src/app/(chats)/chats/layout.tsx
  src/app/layout.tsx
  src/components/RecoilWrapper.tsx
  src/components/header/header.tsx
  src/components/header/navigation.tsx
  src/middleware.ts
  src/store/atoms.js
  src/styles/globals.css
  src/utils/api.ts
Labels: ✨ Feat

#30 Feat: 상품 등록, 상품 상세페이지 기능 구현
  next.config.mjs
  package-lock.json
  package.json
  src/app/(products)/products/[id]/loading.tsx
  src/app/(products)/products/[id]/page.tsx
  src/app/(products)/products/error.tsx
  src/app/constants.ts
  src/app/layout.tsx
  src/app/search/page.tsx
  src/components/ProductCard.tsx
  src/components/atom/MRadio.tsx
  src/components/header/category-list.tsx
  src/components/products/ProductCard/CardLabel.module.css
  src/components/products/ProductCard/CardLabel.tsx
  src/components/products/ProductCard/ProductCard.module.css
  src/components/products/ProductCard/ProductCard.tsx
  src/components/products/ProductDetailInfo.module.css
  src/components/products/ProductDetailInfo.tsx
  src/components/products/ProductsNewForm.module.css
  src/components/products/ProductsNewForm.tsx
  src/components/search/ProductSearchFilter.module.css
  src/components/search/ProductSearchFilter.tsx
  src/utils/common.ts
  src/utils/product.ts
Labels: ✨ Feat

#34 Feature/#32
  src/app/search/page.tsx
  src/components/modal/BidHistoryModal.module.css
  src/components/modal/BidHistoryModal.tsx
  src/components/modal/BidModal.tsx
  src/components/modal/PointNotEnoughModal.tsx
  src/components/modal/modalStyle.tsx
  src/components/products/ProductDetailInfo.module.css
  src/components/products/ProductDetailInfo.tsx
  src/components/products/ProductsNewForm.tsx
  src/styles/globals.css
Labels: ✨ Feat

#33 Feature/#28
  src/app/(chats)/chats/[id]/page.module.css
  src/app/(chats)/chats/[id]/page.tsx
  src/app/(chats)/chats/layout.module.css
  src/components/chats/Chats.tsx
Labels: ✨ Feat

#38 Feature/#35
  package-lock.json
  package.json
  src/app/(products)/products/[id]/page.tsx
  src/app/page.module.css
  src/app/page.tsx
  src/app/search/page.module.css
  src/app/search/page.tsx
  src/components/header/category-list.tsx
  src/components/header/header.module.css
  src/components/header/header.tsx
  src/components/header/navigation.tsx
  src/components/products/ProductCard/CardLabel.tsx
  src/components/products/ProductCard/ProductCard.module.css
  src/components/products/ProductCard/ProductCard.tsx
  src/components/products/ProductDetailInfo.module.css
  src/components/products/ProductDetailInfo.tsx
  src/styles/globals.css
  src/utils/common.ts
  src/utils/product.ts
Labels: ✨ Feat

#40 Feature/#39
  .env
  next.config.mjs
  src/app/(auth)/auth/join/page.tsx
  src/app/(auth)/auth/layout.module.css
  src/app/(auth)/auth/login/kakao/page.tsx
  src/app/(auth)/auth/login/page.module.css
  src/app/(auth)/auth/login/page.tsx
  src/components/header/category-list.module.css
  src/components/header/header-top.tsx
  src/components/header/header.tsx
  src/components/header/navigation.module.css
  src/components/header/navigation.tsx
  src/components/modal/LogoutModal.tsx
Labels: ✨ Feat

#41 [#27] Feat : 공지하상 페이징 완료
  src/app/(notice)/notice/page.module.css
  src/app/(notice)/notice/page.tsx
  src/app/(qna)/page.module.css
  src/app/(qna)/page.tsx
Labels: ✨ Feat

#42 [#28] Faq 리스트 조회,페이징,아코디언 기능 구현
  src/app/(notice)/notice/faq/page.module.css
  src/app/(notice)/notice/faq/page.tsx
Labels: ✨ Feat

#46 Feature/#45
  src/app/(products)/products/[id]/page.tsx
  src/app/search/page.module.css
  src/app/search/page.tsx
  src/components/modal/ProductReportModal.tsx
  src/components/products/ProductDetailInfo.tsx
  src/components/products/ProductsNewForm.tsx
  src/styles/modal/ProductReportModal.module.css
  src/utils/api.ts
Labels: ✨ Feat

#49 Feature/#37-2
  package-lock.json
  package.json
  src/app/(chats)/chats/[id]/page.module.css
  src/app/(chats)/chats/[id]/page.tsx
  src/components/chats/Chats.tsx
  src/components/products/ProductDetailInfo.tsx
Labels: ✨ Feat

#51 Feature/#47
  package-lock.json
  package.json
  src/app/(products)/products/[id]/edit/page.tsx
  src/components/modal/AuctionWinnerModal.tsx
  src/components/products/ProductDetailInfo.tsx
  src/components/products/ProductsNewForm.tsx
Labels: ✨ Feat

#53 Feature/#52
  .env
  src/components/header/header.tsx
  src/components/header/navigation.tsx
  src/components/modal/LogoutModal.tsx
  src/components/modal/PaymentModal.tsx
  src/components/products/ProductDetailInfo.tsx
  src/hooks/useModal.ts
  src/hooks/useUserInfo.ts
  src/store/atoms.js
Labels: ✨ Feat

#55 Feature/#50 안전결제 버튼 & 메시지 구현
  package-lock.json
  src/app/(chats)/chats/[id]/page.module.css
  src/app/(chats)/chats/[id]/page.tsx
  src/app/(chats)/chats/layout.module.css
  src/app/(chats)/chats/layout.tsx
  src/components/chats/Chats.tsx
Labels: ✨ Feat

#54 [#43] Fate
  src/app/(notice)/notice/page.tsx
  src/app/(qna)/page.module.css
  src/app/(qna)/page.tsx
  src/app/constants.ts
  src/app/qna/page.module.css
  src/app/qna/page.tsx
  src/utils/product.ts
Labels: ✨ Feat

#61 [#56] Feat: 팔로워 / 팔로잉 목록 조회/추가/해제
  package-lock.json
  src/app/(chats)/chats/[id]/page.tsx
  src/app/(shop)/shop/follower/page.module.css
  src/app/(shop)/shop/follower/page.tsx
  src/app/(shop)/shop/following/page.module.css
  src/app/(shop)/shop/following/page.tsx
  src/components/shop/followCard.module.css
  src/components/shop/followCard.tsx
Labels: ✨ Feat

#65 Fix/#57
  next.config.mjs
  package-lock.json
  package.json
  src/app/(shop)/shop/payments/page.tsx
  src/components/chats/Chats.tsx
  src/components/header/header.tsx
  src/components/header/navigation.module.css
  src/components/header/navigation.tsx
  src/components/products/ProductCard/ProductCard.module.css
  src/components/products/ProductCard/ProductCard.tsx
  src/components/products/ProductDetailInfo.tsx
  src/components/products/ProductsNewForm.module.css
  src/components/products/ProductsNewForm.tsx
  src/components/shop/shop-menubar.tsx
  src/middleware.ts
Labels: 🔮 Fix, ✨ Feat

#62 [#44]Feat : 회원정보 수정,조회 기능 구현
  src/app/(shop)/shop/profile/page.module.css
  src/app/(shop)/shop/profile/page.tsx
  src/app/(shop)/shop/update/page.module.css
  src/app/(shop)/shop/update/page.tsx
  src/components/shop/shop-menubar.tsx
Labels: ✨ Feat

#67 [#64] 팔로우/팔로잉 목록 페이징 처리(무한 스크롤로) 구현
  package-lock.json
  src/app/(shop)/shop/follower/page.tsx
  src/app/(shop)/shop/following/page.tsx
  src/components/shop/followCard.tsx
Labels: ✨ Feat

#68 [#60] Feat 공지사항 추가 수정 삭제 기능 구현
  src/app/(chats)/chats/[id]/page.tsx
  src/app/(notice)/notice/[id]/edit/page.module.css
  src/app/(notice)/notice/[id]/edit/page.tsx
  src/app/(notice)/notice/new/page.module.css
  src/app/(notice)/notice/new/page.tsx
  src/app/(notice)/notice/page.module.css
  src/app/(notice)/notice/page.tsx
  src/app/qna/page.tsx
  src/app/qna/qnainquiry/qnainquiry.tsx
  src/components/etc/etcsidebar.tsx
  src/store/atoms.js
Labels: ✨ Feat

#73 [#70] Feat 1대1 채팅방 마지막 메시지 / 날짜 표시 기능
  src/app/(chats)/chats/[id]/page.tsx
  src/components/chats/Chats.tsx
  src/store/atoms.js
Labels: ✨ Feat

#75 [#72] Fix 공지사항 필수값체크, 비어있을시 메시지, 타이틀 입력안되는 버그 수정
  src/app/(notice)/notice/[id]/edit/page.tsx
  src/app/(notice)/notice/new/page.tsx
  src/app/(notice)/notice/page.module.css
  src/app/(notice)/notice/page.tsx
  src/app/qna/qnainquiry/qnainquiryhistory.tsx
Labels: 🔮 Fix

#76 [#69] 공지사항 답변 기능 추가 및 게시글 0개일시 문구 추가
  src/app/(notice)/notice/new/page.module.css
  src/app/qna/page.module.css
  src/app/qna/page.tsx
  src/app/qna/qnainquiry/qnainquiry.tsx
  src/app/qna/qnainquiry/qnainquiryhistory.tsx
  src/app/qna/qnainquiry/qnamanagerhistory.tsx
Labels: 🔮 Fix, ✨ Feat

#77 Feature/#74
  src/app/(chats)/chats/[id]/page.module.css
  src/app/(chats)/chats/[id]/page.tsx
  src/components/modal/SafePayModal.module.css
  src/components/modal/SafePayModal.tsx
Labels: ✨ Feat

#79 [#78] 1:1 문의 답변완료,미등록 표시되도록 변경
  src/app/qna/page.module.css
  src/app/qna/qnainquiry/qnainquiryhistory.tsx
  src/app/qna/qnainquiry/qnamanagerhistory.tsx
Labels: 🔮 Fix

#84 [#80] Feat : 관심상품 목록 퍼블리싱 / 조회 / 추가&삭제
  src/app/(shop)/shop/[id]/favorites/page.module.css
  src/app/(shop)/shop/[id]/favorites/page.tsx
Labels: ✨ Feat

#82 Feature/#66 자주묻는질문 등록 수정 삭제기능 구현
  src/app/(notice)/notice/[id]/edit/page.tsx
  src/app/(notice)/notice/faq/page.tsx
  src/app/(notice)/notice/new/page.tsx
  src/app/faq/edit/[id]/page.module.css
  src/app/faq/edit/[id]/page.tsx
  src/app/faq/newfaq/page.module.css
  src/app/faq/newfaq/page.tsx
  src/app/faq/page.module.css
  src/app/faq/page.tsx
  src/components/etc/etcsidebar.tsx
Labels: ✨ Feat

#86 Feature/#83 진행,판매중 경매 퍼블리싱&기능구현
  src/app/(shop)/shop/[id]/auctions/page.module.css
  src/app/(shop)/shop/[id]/auctions/page.tsx
  src/app/(shop)/shop/[id]/bids/page.module.css
  src/app/(shop)/shop/[id]/bids/page.tsx
  src/app/constants.ts
Labels: ✨ Feat

#87 [#85] Fix : 1:1채팅 안전거래 수락/거부 버튼 뜬 이후 버튼 누르기 전에 채팅치면 버튼 사라지는 버그 수정
  src/app/(chats)/chats/[id]/page.tsx
Labels: 🔮 Fix

#91 [#90] 상품 이미지 채팅방에 적용
  src/app/(chats)/chats/[id]/page.tsx
  src/components/chats/Chats.tsx
Labels: ✨ Feat

#93 [#92] 상품 상세페이지에서 판매자 팔로우 여부 조회 / 팔로우 추가or해제
  src/components/products/ProductDetailInfo.module.css
  src/components/products/ProductDetailInfo.tsx
Labels: ✨ Feat

#96 [Fix] #95 1대1 채팅 메시지 공백 못보내게 수정
  src/app/(chats)/chats/[id]/page.tsx
Labels: 🔮 Fix

#98 [#97] fix 관심상품 목록 수 새로고침 없이 즉각적으로 변경되도록 / followCard.tsx 주석 제거
  src/app/(shop)/shop/[id]/favorites/page.tsx
  src/components/shop/followCard.tsx
Labels: 🔮 Fix

#103 [fix] #100 채팅방 관련 오류들 수정
  src/app/(chats)/chats/[id]/page.tsx
Labels: 🔮 Fix

#105 Fix/#104 채팅방/ 팔로우/팔로잉 오류 수정
  src/app/(chats)/chats/[id]/page.tsx
  src/app/(shop)/shop/[id]/favorites/page.module.css
  src/app/(shop)/shop/[id]/favorites/page.tsx
  src/app/(shop)/shop/[id]/follower/page.tsx
  src/app/(shop)/shop/[id]/following/page.tsx
  src/components/chats/Chats.tsx
  src/components/shop/followCard.tsx
Labels: 🔮 Fix

#106 [#101] Fix 1:1문의 등록시 목록으로 이동 관리자가 1:1문의 조회시 userid 표시대신 email 표시로 변경
  src/app/qna/page.tsx
  src/app/qna/qnainquiry/qnainquiry.tsx
  src/app/qna/qnainquiry/qnamanagerhistory.tsx
Labels: 🔮 Fix

#107 Fix/#99 회원정보수정 비밀번호, 회원탈퇴 기능 수정
  src/app/(shop)/shop/[id]/profile/page.tsx
Labels: 🔮 Fix

#109 [#108] Fix : 회원정보수정 새비밀번호, 새비밀번호 확인 및 회원탈퇴 기능 수정
  src/app/(shop)/shop/[id]/profile/page.tsx
Labels: 🔮 Fix

#111 [#110] Fix 공백입력시 등록가능했던 버그 수정, 판매,구매내역 가격 오류 수정
  src/app/(notice)/notice/new/page.tsx
  src/app/(shop)/shop/[id]/buy/page.tsx
  src/app/(shop)/shop/[id]/sell/page.tsx
  src/app/qna/qnainquiry/qnainquiry.tsx
  src/components/atom/MRadio.tsx
Labels: 🔮 Fix

#114 #113 Fix 답변에 공백 입력 불가능하게 변경
  src/app/qna/qnainquiry/qnamanagerhistory.tsx
Labels: 🔮 Fix

#116 [#112] Fix : 비밀번호 오류메세지 초록->빨강, 소개글 textarea 부분 css 수정
  src/app/(shop)/shop/[id]/profile/page.module.css
  src/app/(shop)/shop/[id]/profile/page.tsx
Labels: 🔮 Fix

#118 [#117] 공지사항 css 수정
  src/app/(notice)/notice/page.module.css
  src/app/(notice)/notice/page.tsx
Labels: 🔮 Fix

#122 [fix] #121 채팅방 css 수정
  src/app/(chats)/chats/[id]/page.module.css
  src/app/(chats)/chats/[id]/page.tsx
  src/app/(chats)/chats/layout.module.css
  src/components/chats/Chats.tsx
Labels: 🔮 Fix

#124 [#feat] 123 채팅방 새로고침 버튼 기능 구현
  src/app/(chats)/chats/[id]/page.tsx
  src/components/chats/Chats.tsx
  src/store/atoms.js
Labels: ✨ Feat

#126 [#125] Fix 공지사항 글자 이상 해결
  src/app/(notice)/notice/page.module.css
Labels: 🔮 Fix

#128 [fix] 127 채팅방 버튼 css 수정
  src/app/(chats)/chats/[id]/page.module.css
  src/app/(chats)/chats/[id]/page.tsx
Labels: 🔮 Fix

#130 [feat, fix] 대화 상대방이 판매자인지, 구매자인지 표시+ 새로고침 버튼 버그 수정
  src/app/(chats)/chats/[id]/page.tsx
  src/app/(chats)/chats/layout.module.css
  src/components/chats/Chats.tsx
  src/store/atoms.js
Labels: 🔮 Fix, ✨ Feat

#132 [#131] Fix 공지사항 사이드바 현재페이지에 맞춰 파란색으로 변경
  src/components/etc/etcsidebar.module.css
  src/components/etc/etcsidebar.tsx
Labels: 🔮 Fix

#133 [#119] Fix: FAQ 새글 등록버튼 CSS 수정, FAQ 수정 화면 목록가기 버튼 추가 및 CSS 수정
  src/app/faq/edit/[id]/page.module.css
  src/app/faq/edit/[id]/page.tsx
  src/app/faq/page.module.css
  src/app/faq/page.tsx
Labels: 🔮 Fix

#135 Fix/#134
  src/app/(chats)/chats/[id]/page.tsx
  src/components/chats/Chats.tsx
Labels: 🔮 Fix, ✨ Feat
