Repository TeamFunxtion/fx-frontend, pull requests merged in 2024-06, with the labels that each got.

#139 Fix/#136
  src/app/(chats)/chats/[id]/page.module.css
  src/app/(chats)/chats/[id]/page.tsx
  src/app/(chats)/chats/layout.module.css
  src/components/chats/Chats.tsx
  src/components/modal/SafePayModal.tsx
  src/components/modal/SafePayRequestModal.tsx
Labels: 🔮 Fix, ✨ Feat

#141 [fix]#140 팔로우카드 팔로잉 수 / 상품 수 표시 수정 및 팔로우카드 눌렀을 때, 판매자 페이지 혹은 마이페이지(자신의 팔로우카드 클릭한 경우)로 이동하도록 수정
  src/app/(shop)/shop/[id]/following/page.tsx
  src/components/products/ProductDetailInfo.tsx
  src/components/shop/followCard.module.css
  src/components/shop/followCard.tsx
Labels: 🔮 Fix, ✨ Feat

#144 [fix]#143 채팅방 테두리 선 css 수정
  src/app/(chats)/chats/[id]/page.module.css
  src/app/(chats)/chats/[id]/page.tsx
  src/app/(chats)/chats/layout.module.css
Labels: 🔮 Fix

#142 [#138]fix : FAQ 새글 등록,수정 공백추가 X 기능 수정
  src/app/faq/edit/[id]/page.tsx
  src/app/faq/newfaq/page.tsx
Labels: 🔮 Fix

#146 [feature] #145 마이페이지/게스트페이지 판매자 평점
  src/app/(chats)/chats/[id]/page.tsx
  src/app/(chats)/chats/layout.module.css
  src/components/chats/Chats.tsx
  src/components/shop/shop-info.module.css
  src/components/shop/shop-info.tsx
Labels: ✨ Feat

#150 [fix]148 채팅방 목록 css 수정
  src/app/(chats)/chats/layout.module.css
  src/components/chats/Chats.tsx
Labels: 🔮 Fix

#151 [#149} 1:1문의 전체조회 미답변조회 기능 추가
  src/app/qna/page.module.css
  src/app/qna/qnainquiry/qnamanagerhistory.tsx
Labels: ✨ Feat

#152 [#147] fix : faq 목록가기 버튼 수정 및 css 변경
  src/app/(notice)/notice/[id]/edit/page.module.css
  src/app/(notice)/notice/new/page.module.css
  src/app/faq/edit/[id]/page.module.css
  src/app/faq/edit/[id]/page.tsx
  src/app/faq/newfaq/page.module.css
  src/app/faq/newfaq/page.tsx
  src/app/faq/page.module.css
  src/app/faq/page.tsx
  src/app/qna/page.module.css
Labels: 🔮 Fix

#155 [fix]#154 평점 소수점 표시 제대로 되게 수정
  src/components/shop/shop-info.tsx
Labels: 🔮 Fix

#157 [#156] Fix 1:1문의 답변 오류 해결
  src/app/qna/qnainquiry/qnamanagerhistory.tsx
Labels: 🔮 Fix

#158 [#153] fix : faq 페이지 css 수정
  src/app/(notice)/notice/page.module.css
  src/app/faq/page.module.css
  src/app/faq/page.tsx
Labels: 🔮 Fix
